# Generated by Django 3.2.10 on 2022-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='file',
            field=models.FileField(upload_to='data'),
        ),
        migrations.AlterField(
            model_name='results',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
