# Generated by Django 3.2.10 on 2022-04-02 23:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20220402_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='year',
        ),
        migrations.AlterField(
            model_name='results',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='qualifier', unique=True),
        ),
    ]
